return {
   -- {
   --    "mfussenegger/nvim-dap",
   --    dependencies = {
   --       "rcarriga/nvim-dap-ui",
   --       "theHamsta/nvim-dap-virtual-text",
   --       "nvim-neotest/nvim-nio",
   --       "williamboman/mason.nvim",
   --    },
   --    config = function()
   --       local dap = require("dap")
   --       local ui = require("dapui")
   --
   --       require("dapui").setup()
   --
   --       dap.configurations.lua = {
   --          {
   --             name = "Current file (local-lua-dbg, lua)",
   --             type = "local-lua",
   --             request = "launch",
   --             cwd = "${workspaceFolder}",
   --             program = {
   --                lua = "lua5.1",
   --                file = "${file}",
   --             },
   --             args = {},
   --          },
   --       }
   --       dap.adapters["local-lua"] = {
   --          type = "executable",
   --          command = "node",
   --          args = {
   --             "/home/n451/local-lua-debugger-vscode/extension/debugAdapter.js",
   --          },
   --          enrich_config = function(config, on_config)
   --             if not config["extensionPath"] then
   --                local c = vim.deepcopy(config)
   --                -- 💀 If this is missing or wrong you'll see
   --                -- "module 'lldebugger' not found" errors in the dap-repl when trying to launch a debug session
   --                c.extensionPath = "/home/n451/local-lua-debugger-vscode/"
   --                on_config(c)
   --             else
   --                on_config(config)
   --             end
   --          end,
   --       }
   --
   --       vim.keymap.set("n", "<space>b", dap.toggle_breakpoint)
   --       vim.keymap.set("n", "<space>gb", dap.run_to_cursor)
   --
   --       -- Eval var under cursor
   --       vim.keymap.set("n", "<space>?", function()
   --          require("dapui").eval(nil, { enter = true })
   --       end)
   --
   --       vim.keymap.set("n", "<F1>", dap.continue)
   --       vim.keymap.set("n", "<F2>", dap.step_into)
   --       vim.keymap.set("n", "<F3>", dap.step_over)
   --       vim.keymap.set("n", "<F4>", dap.step_out)
   --       vim.keymap.set("n", "<F5>", dap.step_back)
   --       vim.keymap.set("n", "<F13>", dap.restart)
   --
   --       dap.listeners.before.attach.dapui_config = function()
   --          ui.open()
   --       end
   --       dap.listeners.before.launch.dapui_config = function()
   --          ui.open()
   --       end
   --       dap.listeners.before.event_terminated.dapui_config = function()
   --          ui.close()
   --       end
   --       dap.listeners.before.event_exited.dapui_config = function()
   --          ui.close()
   --       end
   --    end,
   -- },
}
