vim.keymap.set("n", "<leader>sc", "<cmd>SCNvimStart<CR>")
-- vim.lsp.start({
--    name = "sc-language-server",
--    cmd = {
--       "sc-language-server",
--       "--sclang-path",
--       "/usr/bin/sclang",
--       "--config-path",
--       "/mnt/c/Users/N3OARC/AppData/Local/SuperCollider/sclang_conf.yaml",
--    },
--    root_dir = "/home/n451/",
--    capabilities = vim.lsp.protocol.make_client_capabilities(),
--    -- on_attach = function()
--    --    vim.keymap.set("n", "K", vim.lsp.buf.hover, { buffer = 0 })
--    --    vim.keymap.set("n", "gd", vim.lsp.buf.definition, { buffer = 0 })
--    --    vim.keymap.set("n", "gt", vim.lsp.buf.type_definition, { buffer = 0 })
--    --    vim.keymap.set("n", "gi", vim.lsp.buf.implementation, { buffer = 0 })
--    --    vim.keymap.set("n", "<leader>r", vim.lsp.buf.rename, { buffer = 0 })
--    --    vim.keymap.set("n", "<leader>ca", vim.lsp.buf.code_action, { buffer = 0 })
--    --    vim.keymap.set("n", "<Up>", vim.diagnostic.goto_prev, { buffer = 0 })
--    --    vim.keymap.set("n", "<Down>", vim.diagnostic.goto_next, { buffer = 0 })
--    -- end,
-- })
-- print("tried!")
