# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.38.3" # rocks.nvim can also manage itself :D
"rocks-git.nvim" = "2.2.0"
"kanagawa.nvim" = "scm"
"hardtime.nvim" = "scm"
harpoon = "scm"
"oil.nvim" = "2.12.2"
"telescope.nvim" = "scm"
neogit = "1.0.0"
nvim-lspconfig = "1.0.0"
"mason-lspconfig.nvim" = "1.31.0"
"mason.nvim" = "1.10.0"
"conform.nvim" = "8.1.0"
"noice.nvim" = "4.5.1"
"mini.nvim" = "0.9.0"
"rocks-treesitter.nvim" = "1.1.2"
"which-key.nvim" = "3.13.2"
"trouble.nvim" = "3.6.0"
"gitsigns.nvim" = "0.9.0"
nvim-cmp = "scm"
tree-sitter-markdown = "scm"
tree-sitter-xml = "scm"
tree-sitter-html = "scm"
cmp-path = "scm"
cmp-cmdline = "scm"
tree-sitter-regex = "scm"
tree-sitter-bash = "scm"
"todo-comments.nvim" = "1.3.0"
"tmux.nvim" = "scm"
"render-markdown.nvim" = "7.0.0"
"zen-mode.nvim" = "1.4.0"
"plenary.nvim" = "scm"
tree-sitter-query = "scm"
tree-sitter-luadoc = "scm"
"gruvbox.nvim" = "2.0.0"
nvim-web-devicons = "0.100"
"lualine.nvim" = "scm"
cmp-nvim-lsp = "scm"
cmp-buffer = "scm"
catppuccin = "0.1.0"
"tokyonight.nvim" = "4.8.0"
"copilot.lua" = "scm"
copilot-cmp = "scm"
neotest-busted = "0.2.0"
"lazydev.nvim" = "1.8.0"
tree-sitter-elixir = "scm"
"rime.nvim" = "0.0.1-1"
"repeat.vim" = "1.2"
"leap.nvim" = "scm"
tree-sitter-c = "scm"

[config]
plugins_dir = "plugins/"
auto_setup = false

[plugins."clean.nvim"]
git = "drybalka/clean.nvim"
